# Generated by Django 3.2.2 on 2021-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('Angorá', 'Angorá'), ('Maine Coon', 'Maine Coon'), ('Siamês', 'Siamês'), ('Bengala', 'Bengala'), ('Ragdoll', 'Ragdoll'), ('Persa', 'Persa')], max_length=100, verbose_name='Raça')),
                ('location_origin', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=100, verbose_name='Local de Origem')),
                ('coat_length', models.PositiveSmallIntegerField(verbose_name='Comprimento da Pelagem')),
                ('body_type', models.CharField(choices=[('Cobby', 'Cobby'), ('Médio', 'Médio'), ('Estrangeiro', 'Estrangeiro'), ('Semi-Estrangeiro', 'Semi-Estrangeiro')], max_length=100, verbose_name='Tipo de Corpo')),
                ('pattern', models.CharField(blank=True, max_length=100, null=True, verbose_name='Padrão')),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
                'ordering': ['id'],
            },
        ),
    ]
